### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by alexandra-chron** [ahmetustun/udapter#2]
Hi, thanks for open-sourcing your work. :) 

I am running this `scripts/concat_ud_data.sh`, after installing the dependencies mentioned in the requirements file in a conda virtual environment. First, I got an error from package `six`, which was `ModuleNotFoundError: No module named 'six.moves'; 'six' is not a package`. I resolved this following this [link](https://github.com/home-assistant-ecosystem/home-assistant-cli/issues/166#issuecomment-462814286). I also had to install `tqdm`. Then I got another missing package error, namely ` import lang2vec.lang2vec as l2v
ModuleNotFoundError: No module named 'lang2vec'`. I installed it and now it is running!

Add these in the instructions or the requirements file, if possible. Just thought I would send this because other  people will probably face the same issues.

**Comment by ahmetustun** [comment]
hi, thanks for pointing the issues, I added those into the requirements file!
